test:
  adapter: postgresql
  database: dryclean_test
  host: localhost
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  database: dryclean_development
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: postgresql