development:
  adapter: postgresql
  database: dryclean_development
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: dryclean_production
  host: localhost
  pool: 5
  timeout: 5000